version: 2
# log-file: /Users/balintfulop/Temp/efm.log
# log-level: 1
root-markers:
  - .git/
  - package.json
  - .eslintrc.js
  - .eslintrc.cjs
  - tsconfig.json

tools:
  eslint_d: &eslint_d
    lint-command: 'eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    lint-ignore-exit-code: true
    format-command: 'eslint_d -f visualstudio --fix-to-stdout --stdin --stdin-filename=${INPUT}'
    format-stdin: true

languages:
  javascript:
    - <<: *eslint_d
  javascriptreact:
    - <<: *eslint_d
  javascript.jsx:
    - <<: *eslint_d
  typescript:
    - <<: *eslint_d
  typescript.tsx:
    - <<: *eslint_d
  typescriptreact:
    - <<: *eslint_d
